# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XC9QHICC92-TlKuw65NqeYC1a5W80EkG
"""
import csv
import io
import pandas as pd
from graphviz import Source
#from google.colab import files
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.tree import export_graphviz
from matplotlib import pyplot as plt

#covid_data = files.upload()

#data = pd.read_csv(io.BytesIO(covid_data+'covid.csv'))
data = pd.read_csv(r'C:/Users/Chris/Desktop/covid_test/covid.csv')

data.head()

data_copy = data.copy()
data_copy.head()

data_copy = data_copy.drop(columns=['id'])
data_copy = data_copy.drop(columns=['entry_date'])
data_copy = data_copy.drop(columns='date_symptoms')
deceased  = [0]* data_copy.shape[0]
for i in range(data_copy.shape[0]):
  if data_copy['date_died'][i] != "9999-99-99":
    deceased[i] = 1


data_copy.head()

training_set = data_copy.copy()
training_set['deceased'] = deceased
training_set = training_set.drop(columns=['date_died'])
training_set.describe()

X = training_set.iloc[:,:19].copy()
X.head()

Y = training_set.iloc[:,-1]
Y.head()

X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size=0.3,
                                                 random_state = 42)

from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
clf=RandomForestClassifier(n_estimators=1000)
clf.fit(X_train,Y_train)
y_pred=clf.predict(X_test)

import joblib
joblib.dump(clf, 'model.pkl')